#!/usr/bin/python
#  filter to add dashes, used by ~/bin/plannew
from sys import stdin
import re
m = re.compile(" _")
d = "-" * 71
for line in stdin:
    l = line.rstrip()
    if m.search(l):
        print d
        print l
    else:
        print l
print d
