#!/bin/bash
#  print mail folders sorted on time, filtered for today
cd ~/bin-mail
tod=`date '+%b %e'`
echo
date '+            now  %H:%M:%S' 
echo
ls -lt ~/Mail | grep -v "^total" | grep -F "$tod" | awk -f ccr.awk
echo
laflp
echo
dsh 31 | mio 4
