#!/bin/bash
cd ~/bin-mail
tod=`date '+%b %e'`
echo
date '+            now  %H:%M' 
echo
ls -lt ~/Mail | grep -v "^total" | grep -F "$tod" | awk -f ccr.awk
echo
laflp
#ets `ttt` `laflp | awk '{ print $3 }'` | mio 21
echo
dsh 31 | mio 4
