#!/bin/bash
#  ccr fancified (lists today's mail folders)
clear
b
psf=$(( ( `tput cols` - 75 ) / 2 - 2))
tsl=`tput lines`
loo=`ccr | wc -l`
dp=$(( (tsl - loo) / 3  - 5))
if test $dp -gt 0; then
    b $dp
fi
ccr | mio $(( psf + 18 ))
b
epl | mio $(( psf + 18 ))
