#!/bin/bash
#  how long since the last update?
ldh=$(tail -1 ~/.vim/version.log | cut -c1-17)
lv=$(tail -1 ~/.vim/version.log | cut -c20- )
{
    echo "it's been"
    etol "$ldh"
    echo "since build of $lv"
} | mio 3
