#!/usr/bin/python
#  is this string more than 10 hours in the past?  used by hlslt
from datetime import datetime
from pytz import timezone
from sys import argv, exit
#
#  f and s are the first and second dates
#  f1 and s1 are the time-zone aware versions
#
ctz = timezone('US/Central')
dfm = "%Y-%b-%d %H:%M"   #  date format
hma = len(argv)          #  how many arguments?
if hma < 2:
    print "itsmt requires a datetime string"
    exit(1)

s = datetime.now()
s1 = ctz.localize(s)
try:
    f = datetime.strptime(argv[1], dfm)
    f1 = ctz.localize(f)
except ValueError:
    print "cannot parse %s as datetime" % argv[1]
    exit(1)

d = s1 - f1
hours = d.seconds / 3600

if d.days > 0 or hours > 9:
    print "GToE"
else:
    print "LT"
