#!/bin/bash
#  make vim
cd ~/.build/vim/vim
date '+%Y-%b-%d %H:%M' >> ../make.log
#echo 'DISTCLEAN' >> ../make.log
#make distclean 2>&1 | tee -a ../make.log
#dsh >> ../make.log
#echo 'MAKE' >> ../make.log
make 2>&1 | tee -a ../make.log
dsh >> ../make.log
