#!/bin/bash
cd ~/.build/vim/vim
rm -f src/auto/config.cache
date '+%Y-%b-%d %H:%M' >> ../configure.log
./configure --with-features=huge --with-compiledby=toothpik@home --enable-gui=gtk2 2>&1 | tee -a ../configure.log
dsh 60 >> ../configure.log
