#!/bin/bash
#  myconfigure whacks the old config.cash so it always works
cd ~/.build/vim/vim
rm -f src/auto/config.cache
date '+%Y-%b-%d %H:%M' >> ../configure.log
#  with python:
#./configure --with-features=normal --with-compiledby=toothpik@home --enable-pythoninterp=dynamic --enable-gui=gtk2 2>&1 | tee -a ../configure.log
#
#  with perl:
#./configure --with-features=normal --with-compiledby=toothpik@home --enable-perlinterp --enable-gui=gtk2 2>&1 | tee -a ../configure.log
#
#  with no extra interpreters:
./configure --with-features=normal --with-compiledby=toothpik@home --enable-gui=gtk2 2>&1 | tee -a ../configure.log
dsh 60 >> ../configure.log
