#!/bin/bash
#  u - hg pull
#  you will want to tail -f the update.log in case there are queries from mercurial
cd ~/.build/vim/vim
dds >> ../update.log
hg pull 2>&1 >> ../update.log
dsh >> ../update.log
