#!/bin/bash
#  u2 - hg merge
cd ~/.build/vim/vim
date '+%Y-%b-%d %H:%M' 2>&1 >> ../update.log
if test $# -lt 1 ; then
    mt=`cs`
else
    mt=$1
fi
echo "about to hg merge $mt" >> ../update.log
hg merge $mt 2>&1            >> ../update.log
dsh                          >> ../update.log
