#!/bin/bash
#  u3 - hg commit
cd ~/.build/vim/vim
dt=`date '+%Y-%b-%d %H:%M'`
echo $dt >> ../update.log
if [ $# -eq 0 ]; then
    echo "about to hg commit" >> ../update.log
    hg commit -m "$dt -- updates from bram" 2>&1 >> ../update.log
else
    echo "about to hg commit $@" >> ../update.log
    hg commit "$@" 2>&1 >> ../update.log
fi
dsh >> ../update.log
