#!/usr/bin/perl
#  current fiscal month -- for use by ~/bin/lfy
open(DAT, '-');
while ($fms = <DAT>) {
    chop($fms);
    $fm = $fms + 1;
    if ($fm == 13) { $fm = 1; }
    print "$fm\n";
}
close(DAT);
